# Generated by Django 5.1.2 on 2024-10-21 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название товара')),
                ('style', models.CharField(max_length=50, verbose_name='Стиль')),
                ('facade_material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Материал фасадов')),
                ('body_material', models.CharField(blank=True, max_length=50, null=True, verbose_name='Материал корпуса')),
                ('table_top', models.CharField(blank=True, max_length=50, null=True, verbose_name='Столешница')),
                ('accessories', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фурнитура')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='Цена')),
                ('description', models.TextField(max_length=500, verbose_name='Описание товара')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='madex.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Изображение')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='madex.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Изображение продукта',
                'verbose_name_plural': 'Изображение продукта',
            },
        ),
    ]
