# Generated by Django 5.1.2 on 2024-11-25 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madex', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madex.product', verbose_name='Продукт'),
        ),
    ]
