# Generated by Django 5.1.2 on 2024-11-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madex', '0005_alter_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='products/', verbose_name='Главное фото'),
            preserve_default=False,
        ),
    ]
